# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration

In [4]:
print("NumPy version:", np.__version__)

# Print NumPy configuration (BLAS, LAPACK, etc.)
np.show_config()

NumPy version: 2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: 

#### 3. Create a null vector of size 10

In [5]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [7]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.size)

5


#### 5.  How to get the documentation of the numpy add function from the command line?

In [8]:
np.add?

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [9]:
v = np.zeros(10)
v[4] = 1   # 5th position (index starts from 0)

print(v)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [10]:
v = np.arange(10, 50)
print(v)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last)

In [11]:
v = np.array([1, 2, 3, 4, 5])
reversed_v = v[::-1]
print(reversed_v)


[5 4 3 2 1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [12]:
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [13]:
arr = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(arr)

print(indices)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix

In [14]:
arr = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(arr)

print(indices)

(array([0, 1, 4]),)


#### 12. Create a 3x3x3 array with random values

In [16]:

arr = np.random.random((3, 3, 3))
print(arr)


[[[0.36997871 0.08382752 0.75050695]
  [0.06220624 0.28170237 0.54400011]
  [0.88554604 0.84315378 0.67277403]]

 [[0.60962003 0.05839312 0.26799369]
  [0.98233463 0.50424752 0.14744528]
  [0.78741046 0.1770895  0.1675201 ]]

 [[0.37271129 0.339278   0.68402668]
  [0.63978908 0.51666639 0.43395311]
  [0.83158642 0.01956882 0.94556915]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [17]:
arr = np.random.random((10, 10))

# Find minimum and maximum values
min_val = arr.min()
max_val = arr.max()

print("Array:\n", arr)
print("Minimum value:", min_val)
print("Maximum value:", max_val)


Array:
 [[6.86081389e-01 9.30640625e-01 1.22407998e-01 3.26796169e-01
  7.27854308e-01 8.97246985e-01 1.05683021e-01 7.27880344e-01
  3.64972378e-01 9.90248723e-01]
 [4.50797483e-01 6.38932752e-01 1.62903191e-02 4.32604582e-02
  1.36078998e-01 4.55540930e-01 1.99367317e-02 9.83295289e-01
  1.54949351e-01 6.38055670e-01]
 [9.11738950e-01 1.91570713e-01 1.58693424e-01 8.09308005e-01
  8.03956371e-01 9.82366108e-01 4.50713251e-01 9.04866568e-01
  8.20584629e-02 7.26151496e-01]
 [4.12946318e-02 7.20155136e-01 4.14208599e-01 3.69360096e-01
  4.26380675e-01 4.99387276e-01 7.73601873e-01 7.03373677e-01
  4.34716670e-01 7.53050505e-01]
 [7.36921403e-01 4.62818993e-02 1.53606379e-01 1.65178648e-01
  4.55506870e-01 9.38852076e-01 1.98377992e-01 5.24684962e-01
  9.19176556e-01 8.22479566e-01]
 [5.11921772e-01 6.07422445e-01 1.77695713e-01 9.35502712e-01
  8.89868723e-01 1.61615144e-01 4.08595996e-02 3.77936378e-01
  1.43211258e-02 8.77904021e-01]
 [2.17533631e-02 2.10428335e-01 3.76388374e-01 6.8

#### 14. Create a random vector of size 30 and find the mean value

In [18]:
vec = np.random.random(30)

# Find the mean value
mean_val = vec.mean()

print("Vector:", vec)
print("Mean value:", mean_val)

Vector: [0.52104974 0.13979494 0.71654954 0.00247727 0.20026696 0.82068033
 0.57024619 0.6346554  0.99250427 0.5223334  0.78350978 0.52816461
 0.70538008 0.40310644 0.65351187 0.56519275 0.92275144 0.87830796
 0.66966927 0.13853236 0.17354174 0.23499354 0.16158995 0.24217783
 0.12261135 0.12247359 0.14528377 0.76538671 0.4805945  0.32158562]
Mean value: 0.4712974396989538


#### 15. Create a 2d array with 1 on the border and 0 inside

In [19]:
# Size of the array
n, m = 5, 5   # you can change the size

arr = np.zeros((n, m), dtype=int)
arr[0, :] = 1
arr[-1, :] = 1
arr[:, 0] = 1
arr[:, -1] = 1

print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [20]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Add a border of zeros (width = 1)
bordered = np.pad(arr, pad_width=1, mode='constant', constant_values=0)

print(bordered)

[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [22]:
import numpy as np

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [23]:
# Create a 5x5 zero matrix
mat = np.zeros((5, 5), dtype=int)

# Fill values just below the diagonal
mat[np.arange(1, 5), np.arange(4)] = [1, 2, 3, 4]

print(mat)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [24]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [26]:
print("Index of the 100th element =", (1, 5, 4))


Index of the 100th element = (1, 5, 4)
